version: "3.2"
services:
  banco_talentos:
    build:
      context: .
    container_name: banco_talentos
    volumes: 
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
    environment:
      - CI_ENV=development
    # ports:
    #   - 8000:80
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres
    container_name: postgres_db
    volumes:
      - db-banco-talentos:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: talentos
      # USUARIO PADRÃO: postgres
    ports:
      - 5432:5432
  # redis:
  #   image: redislabs/rejson
  #   container_name: eestado_redisjson
  #   ports:
  #     - 6379:6379
# networks:
#   default:
#     external: true
#     name: eestado_network
volumes:
  db-banco-talentos:
    external: true